name = "yanify-api"
main = "crates/yanify-worker/build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install -q worker-build && cd crates/yanify-worker && worker-build --release"
