[package]
name = "yanify-transform"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
