[package]
name = "yanify-worker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
yanify-transform = { path = "../yanify-transform" }
worker = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
